#version: "3"

services:
  api:
    image: scan:latest
    command: npm run api
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./scan-api/config/local.js:/scan/scan-api/config/local.js
      - ./log/api:/scan/log
      - ./cache:/scan/cache
  open_api:
    image: scan:latest
    command: npm run open_api
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  compiler:
    image: scan:latest
    command: npm run compiler
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./log/compiler:/scan/log
      - ./cache:/scan/cache
  block:
    image: scan:latest
    command: npm run block
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  token_transfer: # token transfer sync
    image: scan:latest
    command: npm run token_transfer
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  token_x: # token misc: holder, total supply; T3525; approval sync;
    image: scan:latest
    command: npm run token_x
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  cfx_transfer: # cfx transfer sync
    image: scan:latest
    command: npm run cfx_transfer
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  pos:
    image: scan:latest
    command: npm run pos
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  epoch:
    image: scan:latest
    command: npm run epoch
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
      - ./public:/scan/public
  stat_task:
    image: scan:latest
    command: npm run stat_task
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  nft_meta:
    image: scan:latest
    command: npm run nft_meta
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
  prune:
    image: scan:latest
    command: npm run prune
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./stat/config/Prod.js:/scan/stat/config/Prod.js
      - ./log:/scan/log
      - ./cache:/scan/cache
