version: "3"

services:
  stat:
    image: node:14.7.0
    volumes:
      - ./:/stat-root
      - ./log/:/log
    network_mode: host
    environment:
      PORT: 8087
    restart: always
    command: node /stat-root/stat/dist/Index.js >> /log/stat.log 2>&1