# api compiler stat block
# token_x token_alone token_misc uniqueAddressStat
# cfx_alone cfx cfxCounterHolderMarker
# pos bill
version: "3"

services:
  api:
    image: node:14.17.5
    volumes:
      - ./:/scan
      - ./log/api:/log
      - ./data/api:/data
    network_mode: host
    restart: always
    command: node /scan/scan-api
  open_api:
    image: node:14.17.5
    volumes:
      - ./:/scan
      - ./log/api:/log
      - ./data/api:/data
    network_mode: host
    restart: always
    command: node /scan/open-api/ApiServer.js


  compiler:
    image: node:14.17.5
    volumes:
      - ./:/scan
      - ./log/compiler:/log
      - ./data/compiler:/cache
    network_mode: host
    restart: always
    command: node /scan/scan-compiler
  stat:
    image: node:14.17.5
    volumes:
      - ./:/stat-root
      - ./log/:/log
    network_mode: host
    environment:
      PORT: 8087
    restart: always
    command: node /stat-root/stat/dist/Index.js
  block:
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/FullBlockSync.js
  stream: # not used
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/StreamSync.js
  token_transfer_alone: # token transfer sync
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/TokenTransferSync.js useConfigRpc -1 10000 # prune
  token_transfer: # token transfer sync
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/TokenTransferSync.js useConfigRpc -1 10000 prune
  token_approval: # token approval sync
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/ApprovalSync.js useConfigRpc -1 10000
  token_3525: # token 3525 sync
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/T3525Sync.js sync useConfigRpc -1 10000
  token_misc: # token misc: holder, total supply
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/service/watcher/BatchBalanceWatcher.js useConfigRpc 500
  uniqueAddressStat: # UniqueAddressStat
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/service/UniqueAddressStat.js useConfigRpc -1 3000
  cfx_transfer_alone: # cfx transfer sync
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/CfxTransferSync.js useConfigRpc -1 10000 # prune streamStat
  cfx_transfer: # cfx transfer sync
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/CfxTransferSync.js useConfigRpc -1 10000 prune streamStat
  cfxCounterHolderMarker:
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/CfxTransferSync.js cfxCounterHolderMarker
  pos:
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/service/pos/PosSync.js
  timer_task:
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/TimerTask.js
  bill:
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/service/watcher/DummyNode.js 1
  pos-not-ready:
    image: node:14.17.5
    network_mode: host
    restart: always
    volumes:
      - ./:/stat-root
    command: node /stat-root/stat/dist/service/pos/PosSync.js http://192.168.8.165:12537 345000
  epoch:
    image: node:14.17.5
    volumes:
      - ./:/stat-root
      - ./log/:/log
    network_mode: host
    environment:
      PORT: 8087
    restart: always
    command: node /stat-root/stat/dist/FullEpochSync.js prune
  epoch_backward:
    image: node:14.17.5
    volumes:
      - ./:/stat-root
      - ./log/:/log
    network_mode: host
    environment:
      PORT: 8087
    restart: always
    command: node /stat-root/stat/dist/FullEpochSync.js backward syncTransfer prune