GET localhost:8087/open/version
###
GET localhost:8087/api/list-account-transaction?address=cfx:aamgvyzht7h1zxdghb9ee9w26wrz8rd3gj837392dp
###
GET localhost:8087/api/list-account-transaction?address=CFX:TYPE.USER:AATFDV8WDFUW8BKCAD0108APN5EZK1DA0Y8MSREF2N
###
GET localhost:8087/api/list-account-transfer20?address=cfx:aajj1b1gm7k51mhzm80czcx31kwxrm2f6jxvy30mvk
###
GET localhost:8087/api/list-account-transfer721?address=cfx:aajj1b1gm7k51mhzm80czcx31kwxrm2f6jxvy30mvk
###
GET localhost:8087/api/list-account-transfer1155?address=cfx:aajj1b1gm7k51mhzm80czcx31kwxrm2f6jxvy30mvk
###