import {DataTypes, Model} from "sequelize";
import {makeId as makeAddrId} from "./HexMap";

export interface Transaction{
    id: number,
    epochHeight: number,
    nonce: number,
    hash: string, //64
    from: string, // 40
    to: string, // 40
    value: number,
    gas: number,
    txIndex: number,
    blockTime: Date,
}
export interface ITransactionDB {
    id: number,
    epochHeight: number,
    nonce: number,
    hash: string, //64
    from: number, // 40
    to: number, // 40
    value: number,
    gas: number,
    txIndex: number,
    blockTime: Date,
}

export class TransactionDB extends Model<ITransactionDB> implements ITransactionDB{
    epochHeight: number;
    from: number;
    hash: string;
    id: number; // id generated by `sync` process.
    nonce: number;
    to: number;
    value: number;
    gas: number;
    txIndex: number;
    blockTime: Date;
    static register(sequelize) {
        TransactionDB.init({
            id: {type: DataTypes.BIGINT, primaryKey: true, allowNull: false, autoIncrement: true},
            epochHeight: {type: DataTypes.BIGINT, allowNull: false},
            hash: {type: DataTypes.CHAR(66), allowNull: false},
            nonce: {type: DataTypes.BIGINT, allowNull: false},
            from: {type: DataTypes.BIGINT, allowNull: false},
            to: {type: DataTypes.BIGINT, allowNull: false},
            value: {type: DataTypes.DECIMAL(36, 0), allowNull: false},
            gas: {type: DataTypes.INTEGER, allowNull: false},
            txIndex: {type: DataTypes.INTEGER, allowNull: false},
            blockTime: {type: DataTypes.DATE, allowNull: false},
        },{
            sequelize: sequelize,
            tableName: 'tx',
            timestamps: false,
            indexes: [{
                name: "from_idx", fields: ["from"]
            }, {
                name: "to_idx", fields: ["to"]
            }, {
                name: 'blockTime', fields: [{name:'blockTime', order: "DESC"}]
            }]
        })
    }

    static async add(tx: Transaction, dbTx = undefined): Promise<ITransactionDB> {
        const fromId = await makeAddrId(tx.from, dbTx);
        const toId = await makeAddrId(tx.to, dbTx);
        // const hashId = await makeAddrId(tx.hash);
        return await TransactionDB.create({
            epochHeight: tx.epochHeight,
            from: fromId.id,
            hash: tx.hash, nonce: tx.nonce, to: toId.id,
            id: tx.id, value: tx.value, gas: tx.gas, txIndex: tx.txIndex,
            blockTime: tx.blockTime
        }, {transaction: dbTx })
    }
}