import {DataTypes, Model} from "sequelize";
import {makeId as makeAddrId} from "./HexMap";

export interface Transaction{
    id?: number,
    epochHeight?: number,
    nonce?: number,
    hash?: string, //64
    from?: string, // 40
    fromId?:number
    to?: string, // 40
    toId?:number
    value?: number,
    gas?: number,
    gasPrice?: number;
    status?: number;
    txIndex?: number,
    blockTime?: Date,
}
export interface ITransactionDB {
    id: number,
    epochHeight: number,
    nonce: number,
    hash: string, //64
    from: number, // 40
    to: number, // 40
    value: number,
    gasPrice: number;
    gas: number,
    status?: number,
    txIndex: number,
    blockTime: Date,
    fromHex?: string
    toHex?: string
}

export class TransactionDB extends Model<ITransactionDB> implements ITransactionDB{
    epochHeight: number;
    from: number;
    hash: string;
    id: number; // id generated by `sync` process.
    nonce: number;
    to: number;
    value: number;
    status:number;
    gas: number;
    gasPrice: number;
    txIndex: number;
    blockTime: Date;
    fromHex?: string;
    toHex?: string;
    static register(sequelize) {
        TransactionDB.init({
            id: {type: DataTypes.BIGINT, primaryKey: true, allowNull: false, autoIncrement: true},
            epochHeight: {type: DataTypes.BIGINT, allowNull: false},
            hash: {type: DataTypes.CHAR(66), allowNull: false},
            nonce: {type: DataTypes.BIGINT, allowNull: false},
            from: {type: DataTypes.BIGINT, allowNull: false},
            to: {type: DataTypes.BIGINT, allowNull: false},
            value: {type: DataTypes.DECIMAL(36, 0), allowNull: false},
            gas: {type: DataTypes.INTEGER, allowNull: false},
            status: {type: DataTypes.INTEGER, allowNull: false, defaultValue: 0},
            gasPrice: {type: DataTypes.BIGINT, allowNull: false, defaultValue: 0},
            txIndex: {type: DataTypes.INTEGER, allowNull: false},
            blockTime: {type: DataTypes.DATE, allowNull: false},
            fromHex: {type: DataTypes.VIRTUAL},
            toHex: {type: DataTypes.VIRTUAL},
        },{
            sequelize: sequelize,
            tableName: 'tx',
            timestamps: false,
            indexes: [{
                name: "from_idx", fields: ["from"]
            }, {
                name: "to_idx", fields: ["to"]
            }, {
                name: 'blockTime', fields: [{name:'blockTime', order: "DESC"}]
            }]
        })
    }
}