openapi: 3.0.0
info:
  title: Conslux Scan Open Api
  description: Conslux Scan Open Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8087'
paths:
  '/api/':
    get:
  '/api/list-account-transaction':
    get:
  '/api/list-account-transfer20':
    get:
  '/api/list-account-transfer721':
    get:
  '/api/list-account-transfer1155':
    get:
  '/api/list-account-assert':
    get:

