export const DataTimeTableList = {
	cfx_holder_daily: {ignore: false,},
	cfx_transfer_2:         {ignore: true,},
	cross_space_stat: {ignore: false,},
	daily_active_addr: {ignore: false,},
	daily_addr: {ignore: false,},
	daily_block_data_stat: {ignore: false,},
	daily_burnt_fee_stat: {ignore: false,},
	daily_cfx_txn: {ignore: false,},
	daily_contract_create: {ignore: false,},
	daily_contract_register: {ignore: false,},
	daily_contract_stat: {ignore: false,},
	daily_nft_holder: {ignore: false,},
	daily_nft_stat: {ignore: false,},
	daily_pos_reward_stat: {ignore: false,},
	daily_pow_reward_stat: {ignore: false,},
	daily_token: {ignore: false,},
	daily_token_txn: {ignore: false,},
	epoch_address_ids: {ignore: true,},
	epoch_hash_cfx_transfer: {ignore: false,},
	epoch_hash_token_transfer_3: {ignore: false,},
	epoch_task_unique_addr: {ignore: false,},
	erc20transfer_3: {ignore: true,},
	full_block: {ignore: false,},
	full_tx: {ignore: true,},
	gas_consumer: {ignore: false,},
	pos_block: {ignore: false,},
	pos_committee: {ignore: false,},
	pos_committee_node: {ignore: false,},
	pos_daily_stat: {ignore: false,},
	pos_daily_stat_mix: {ignore: false,},
	pos_epoch_reward_hash: {ignore: false,},
	pos_gap: {ignore: false,},
	pos_reward: {ignore: false,},
	pos_reward_rank: {ignore: false,},
	pos_tx: {ignore: false,},
	tx_daily: {ignore: false,},
	tx_receiver_daily: {ignore: false,},
	tx_receiver_hourly: {ignore: false,},
	tx_sender_daily: {ignore: false,},
	tx_sender_hourly: {ignore: false,},
	unique_addr: {ignore: true,},
	unique_addr_daily: {ignore: false,},
	unique_addr_hourly: {ignore: false,},


	'abi_info': {ignore: true },
	'abi_stub': {ignore: true },
	'auth_action': {ignore: true },
	'auth_tx_stub': {ignore: true },
	'blacklist': {ignore: true },
	'censor_item': {ignore: true },
	'ens': {ignore: true },
	'nft_id': {ignore: true },
	'rate_key': {ignore: true },
	'search_text': {ignore: true },
	'stat_token_transfer': {ignore: true },
	'token2': {ignore: true },
	'token_auto_detect': {ignore: true },
	'token_quote': {ignore: true },
	'pivot_switch_2': {ignore: true },
	'contract_verify2': {ignore: true },
	'address_cfx_transfer_2': {ignore: true },
	'address_erc1155transfer_3': {ignore: true },
	'address_erc721transfer_3': {ignore: true },
	'address_erc20transfer_3': {ignore: true },
	'address_nft_transfer': {ignore: true },
	'address_nfts': {ignore: true },
	'addr_event_3525': {ignore: true },
	'api_log': {ignore: true },
	'address_tx': {ignore: true },
	'address_nft': {ignore: true },
	'address_transfer': {ignore: true },
	'approval_relation': {ignore: true },
	'cfx_balance': {ignore: true },
	'contract': {ignore: true },
	'contract2': {ignore: true },
	'contract_abi': {ignore: true },
	'contract_verify': {ignore: true },
	'event_3525': {ignore: true },
	'erc1155_addr_amount': {ignore: true },
	'erc1155_data': {ignore: true },
	'erc1155transfer_3': {ignore: true },
	'erc721transfer_3': {ignore: true },
	'error_log': {ignore: true },
	'e_space_hex40': {ignore: true },
	'full_tx_row_mark': {ignore: true },
	'name_tag': {ignore: true },
	'owner_count': {ignore: true },
	'nft_metadata': {ignore: true },
	'nft_balance': {ignore: true },
	'nft_metadata_fts': {ignore: true },
	'nft_mint_2': {ignore: true },
	'nft_transfer': {ignore: true },
	'prune_info': {ignore: true },
	'hex40': {ignore: true },
	'pos_account': {ignore: true },
	'slot_changed_3525': {ignore: true },
	'rate_config': {ignore: true },
	'rate_hit': {ignore: true },
	'req_account': {ignore: true },
	'task_cfx_transfer': {ignore: true },
	'task_event_3525': {ignore: true },
	'task_token_transfer_3': {ignore: true },
	'task_approval': {ignore: true },
	'token': {ignore: true },
	'token_approval': {ignore: true },
	'token_balance': {ignore: true },
	'token_security_audit': {ignore: true },
	'token_security_audit2': {ignore: true },
	'token_slot_3525': {ignore: true },
	'result_cache': {ignore: true },
	'proxy_verify': {ignore: true },
	'pos_account_new': {ignore: true },
	'pos_com_old': {ignore: true },
	'full_miner_block': {ignore: true },
	'block_row_mark': {ignore: true },
	'cfx_transfer_row_mark_2': {ignore: true },
	'cfx_user': {ignore: true },
	'check_epoch_info': {ignore: true },
	'config': {ignore: true },
	'contract_destroy': {ignore: true },
	'contract_user': {ignore: true },
	'epoch_nft_transfer': {ignore: true },
	'full_block_ext': {ignore: true },
	'heart_beat': {ignore: true },
	'hex64': {ignore: true },
	'lock': {ignore: true },
	'epoch': {ignore: true, key: 'epoch' , time: 'timestamp' },
	'pos_account_block': {ignore: true,  },
	'pos_register': {ignore: true,  },
	'slot_3525': {ignore: true,  },
	'trace_create_contract': {ignore: true,  },
	'tx_failed': {ignore: true,  },
	'testTimezone': {ignore: true,  },
	'transfer_count': {ignore: true,  },
	'vote_params': {ignore: true, time: 'timestamp'  },
	'minerblock': {ignore: false, time: 'beginTime'  },
}
