function buildFlow(func) {
  let flow;
  // the returned fn will be called more than once, so <flow> will cache the inner fn (generated by func).
  return async function (options) {
    flow = flow || func(this.app);
    return flow.call(this, options);
  };
}

module.exports = buildFlow;
