version: "3"

services:
  open_api_1:
    container_name: ${SPACE}_OPEN_API_${OPEN_API_PORT_1}
    image: node:14.17.5
    volumes:
      - ../:/scan
    working_dir: /scan
    network_mode: host
    restart: always
    environment:
      - API_PORT=${OPEN_API_PORT_1}
    command: node ./open-api/ApiServer.js
  open_api_2:
    container_name: ${SPACE}_OPEN_API_${OPEN_API_PORT_2}
    image: node:14.17.5
    volumes:
      - ../:/scan
    working_dir: /scan
    network_mode: host
    restart: always
    environment:
      - API_PORT=${OPEN_API_PORT_2}
    command: node ./open-api/ApiServer.js
  open_api_3:
    container_name: ${SPACE}_OPEN_API_${OPEN_API_PORT_3}
    image: node:14.17.5
    volumes:
      - ../:/scan
    working_dir: /scan
    network_mode: host
    restart: always
    environment:
      - API_PORT=${OPEN_API_PORT_3}
    command: node ./open-api/ApiServer.js